"""homework

Revision ID: 1d4c168705f7
Revises: 021c1b18abc6
Create Date: 2026-07-05 19:10:08.359115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4c168705f7'
down_revision: Union[str, Sequence[str], None] = '021c1b18abc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('urgency', sa.Boolean(), nullable=False, server_default=sa.sql.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'urgency')
    # ### end Alembic commands ###
